name: DeliveryMan
main: com.nerotek01.deliveryman.Main
version: ${version}
api-version: 1.13
author: Nerotek01
description: DeliveryMan plugin with MongoDB, Redis, MySQL and SQLite backend support.
softdepend:
  - Votifier
  - PlaceholderAPI
  - MVdWPlaceholderAPI
commands:
  deliveryman:
    description: Main command for DeliveryMan
    aliases: [ udm ]
permissions:
  deliveryman.admin:
    description: Admin permission (reload)
    default: op
  deliveryman.menu:
    description: Allows opening the rewards menu
    default: true
  deliveryman.message1:
    default: true
  deliveryman.vote1:
    default: true
  deliveryman.unique1:
    default: true
  deliveryman.normal:
    default: true
  deliveryman.vip:
    default: op
  deliveryman.vip+:
    default: op
  deliveryman.mvip:
    default: op
  deliveryman.mvip+:
    default: op
