name: Delivery
main: com.nerotek01.deliveryman.Main
version: ${version}
api-version: 1.13
author: Nerotek01
description: Delivery plugin with MongoDB and Redis backend support.
commands:
  rewards:
    description: Open the rewards menu
    aliases: [ reward ]
permissions:
  delivery.daily:
    description: Access to the daily Mystery Dust reward
    default: true
  delivery.default:
    description: Access to the default Mystery Dust reward
    default: true
  delivery.vip:
    description: Access to the VIP Mystery Dust reward
    default: op
  delivery.vip+:
    description: Access to the VIP+ Mystery Dust reward
    default: op
  delivery.mvp:
    description: Access to the MVP Mystery Dust reward
    default: op
  delivery.mvp+:
    description: Access to the MVP+ Mystery Dust reward
    default: op
  delivery.mvp++:
    description: Access to the MVP++ Mystery Dust reward
    default: op
